package bf.ibam.sgrcore.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MatiereAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatiereAllPropertiesEquals(Matiere expected, Matiere actual) {
        assertMatiereAutoGeneratedPropertiesEquals(expected, actual);
        assertMatiereAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatiereAllUpdatablePropertiesEquals(Matiere expected, Matiere actual) {
        assertMatiereUpdatableFieldsEquals(expected, actual);
        assertMatiereUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatiereAutoGeneratedPropertiesEquals(Matiere expected, Matiere actual) {
        assertThat(actual)
            .as("Verify Matiere auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatiereUpdatableFieldsEquals(Matiere expected, Matiere actual) {
        assertThat(actual)
            .as("Verify Matiere relevant properties")
            .satisfies(a -> assertThat(a.getNomMatiere()).as("check nomMatiere").isEqualTo(expected.getNomMatiere()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatiereUpdatableRelationshipsEquals(Matiere expected, Matiere actual) {
        // empty method
    }
}
