package bf.ibam.sgrcore.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReclamationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReclamationAllPropertiesEquals(Reclamation expected, Reclamation actual) {
        assertReclamationAutoGeneratedPropertiesEquals(expected, actual);
        assertReclamationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReclamationAllUpdatablePropertiesEquals(Reclamation expected, Reclamation actual) {
        assertReclamationUpdatableFieldsEquals(expected, actual);
        assertReclamationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReclamationAutoGeneratedPropertiesEquals(Reclamation expected, Reclamation actual) {
        assertThat(actual)
            .as("Verify Reclamation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReclamationUpdatableFieldsEquals(Reclamation expected, Reclamation actual) {
        assertThat(actual)
            .as("Verify Reclamation relevant properties")
            .satisfies(a -> assertThat(a.getNomReclamant()).as("check nomReclamant").isEqualTo(expected.getNomReclamant()))
            .satisfies(a -> assertThat(a.getPrenomReclamant()).as("check prenomReclamant").isEqualTo(expected.getPrenomReclamant()))
            .satisfies(a -> assertThat(a.getNiveauEtude()).as("check niveauEtude").isEqualTo(expected.getNiveauEtude()))
            .satisfies(a -> assertThat(a.getObjetReclamation()).as("check objetReclamation").isEqualTo(expected.getObjetReclamation()))
            .satisfies(a -> assertThat(a.getMotifReclamation()).as("check motifReclamation").isEqualTo(expected.getMotifReclamation()))
            .satisfies(a -> assertThat(a.getJustificatif()).as("check justificatif").isEqualTo(expected.getJustificatif()))
            .satisfies(a -> assertThat(a.getEtatReclamation()).as("check etatReclamation").isEqualTo(expected.getEtatReclamation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReclamationUpdatableRelationshipsEquals(Reclamation expected, Reclamation actual) {
        assertThat(actual)
            .as("Verify Reclamation relationships")
            .satisfies(a -> assertThat(a.getFiliere()).as("check filiere").isEqualTo(expected.getFiliere()))
            .satisfies(a -> assertThat(a.getMatiere()).as("check matiere").isEqualTo(expected.getMatiere()));
    }
}
